server:
  port: 8091
spring:
  cloud:
    sentinel:
      transport:
        port: 9999
        dashboard: 192.168.56.10:8080
    nacos:
      discovery:
        server-addr: 192.168.56.10:8848
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: password
  jpa:
    showSql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect